<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ext_testing"
 *
 * Auto generated by Extension Builder 2016-08-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Testing',
	'description' => 'This extension provides real examples for unit and functional tests',
	'category' => 'example',
	'author' => 'Nicole Cordes',
	'author_email' => 'typo3@cordes.co',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);